Create Readme.md
atapas/fork-me pull request #457
Opened 2023-01-06 09:12 UTC by Rjc0404

# Description

- [ ] I have added a folder(Named it as my GitHub user id)
- [ ] I have added a Readme.md file inside the folder
- [ ] I understand the GitHub Forking Concept fully
123

2023-01-06 09:30 UTC, Rjc0404 commented
>

2023-01-06 09:32 UTC, Rjc0404 reviewed
666

2023-01-06 09:41 UTC, atapas requested changes

2023-01-06 09:41 UTC, atapas commented on 03anjali/Readme.md
>  Hello world!!!🙌
Why is this file changed.

2023-01-06 10:17 UTC, Rjc0404 commented
手抖了。。。。



在 2023-01-06 17:41:36，"Tapas Adhikary" ***@***.***> 写道：

@atapas requested changes on this pull request.

In 03anjali/Readme.md:

> @@ -1,2 +1,3 @@

 Hello world!!!🙌



Why is this file changed.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-08 06:11 UTC, Rjc0404 commented on 03anjali/Readme.md
>  Hello world!!!🙌
sorry How can I fix it

2023-02-08 06:18 UTC, closed without merging